#!/usr/bin/bash

src="/mnt/t/export_sphere/input_1/Beek_26092024/Job_20240926_0724"
tgt="/mnt/d/BLUR_Rivierenland/Blurred/output_1/Beek_26092024/Job_20240926_0724"

usage()
{
   cat << EOF
usage: ${0##*/} [-i input_dir] [-o output_dir] [-v]

This script copies the orientation files to a destination folder.
It also cleans the output directory from JSON files. These are generated by the blurring software.

The options are as follows:
   -i   input directory. By default current directory.
   -o   output directory. By default current directory.
   -v   be verbose
EOF
	exit 1
}

input_dir=$(pwd)
output_dir=$(pwd)

unset verbose

while getopts ":i:o:v" option ; do
   case ${option} in
      "i") input_dir="${OPTARG}"
           ;;
      "o") output_dir="${OPTARG}"
           ;;
      "v") verbose="yes"
           ;;
      *) usage
         ;;
   esac
done

if [[ ! -d "$input_dir" ]] ; then
	echo "$0: input directory $input_dir does not exist" >&2
	exit 1
fi

if [[ ! -d "$output_dir" ]] ; then
	mkdir -p "$output_dir"
fi

pushd "$input_dir" 1>/dev/null

csv_total=0
txt_total=0

find . -type f -name '*.txt' -o -name '*.csv' | \
(
	while read i ; do 
		if [[ -n "$verbose" ]] ; then
			echo "$0: copying orientation file:   $i"
		fi

		orientation_dir="${i%/*.*}"
		orientation_file="${i##*/}"
		
		mkdir -p "$output_dir/$orientation_dir"
		cp "$i" "$output_dir/$orientation_dir/"
		
		if [[ "${orientation_file: -3}" == 'csv' ]] ; then
			csv_total=$((csv_total + 1))
		elif [[ "${orientation_file: -3}" == 'txt' ]] ; then
			txt_total=$((txt_total + 1))
		fi
	done

echo "$0: copied $csv_total external orientation files" >&2
echo "$0: copied $txt_total internal orientation files" >&2
)

popd 1>/dev/null


pushd "$output_dir" 1>/dev/null
if [[ -n "$verbose" ]] ; then
	echo "$0: removing JSON files from output directory" >&2
fi

find . -type f -name *.json -exec rm {} \;
popd 1>/dev/null

exit 0